name: Run Infra Tests

on:
  workflow_call:

jobs:
  infra-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Frontend
        shell: powershell
        run: ./.github/scripts/test-frontend.ps1

      - name: Test Auth API
        shell: powershell
        run: ./.github/scripts/test-auth.ps1

      - name: Test Backend
        shell: powershell
        run: ./.github/scripts/test-backend.ps1
